name: Extreme Tech Seminar
description: nerds learning together
baseurl: 

markdown: redcarpet
highlighter: pygments

disqus: false
google-analytics: false

exclude: ["*.org"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
